// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.mass.tdm.protobuf.tree

@SerialVersionUID(0L)
final case class IdCodePair(
    id: _root_.scala.Int = 0,
    code: _root_.scala.Int = 0,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[IdCodePair] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = id
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(1, __value)
        }
      };
      
      {
        val __value = code
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = id
        if (__v != 0) {
          _output__.writeInt32(1, __v)
        }
      };
      {
        val __v = code
        if (__v != 0) {
          _output__.writeInt32(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withId(__v: _root_.scala.Int): IdCodePair = copy(id = __v)
    def withCode(__v: _root_.scala.Int): IdCodePair = copy(code = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = id
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = code
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(id)
        case 2 => _root_.scalapb.descriptors.PInt(code)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.mass.tdm.protobuf.tree.IdCodePair
    // @@protoc_insertion_point(GeneratedMessage[com.mass.tdm.protobuf.IdCodePair])
}

object IdCodePair extends scalapb.GeneratedMessageCompanion[com.mass.tdm.protobuf.tree.IdCodePair] with scalapb.HasBuilder[com.mass.tdm.protobuf.tree.IdCodePair] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.mass.tdm.protobuf.tree.IdCodePair] with scalapb.HasBuilder[com.mass.tdm.protobuf.tree.IdCodePair] = this
  def merge(`_message__`: com.mass.tdm.protobuf.tree.IdCodePair, `_input__`: _root_.com.google.protobuf.CodedInputStream): com.mass.tdm.protobuf.tree.IdCodePair = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.mass.tdm.protobuf.tree.IdCodePair] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.mass.tdm.protobuf.tree.IdCodePair(
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        code = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TreeProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TreeProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.mass.tdm.protobuf.tree.IdCodePair(
    id = 0,
    code = 0
  )
  final class Builder private (
    private var __id: _root_.scala.Int,
    private var __code: _root_.scala.Int,
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[com.mass.tdm.protobuf.tree.IdCodePair] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __id = _input__.readInt32()
          case 16 =>
            __code = _input__.readInt32()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): com.mass.tdm.protobuf.tree.IdCodePair = {
      com.mass.tdm.protobuf.tree.IdCodePair(
        id = __id,
        code = __code,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[com.mass.tdm.protobuf.tree.IdCodePair, com.mass.tdm.protobuf.tree.IdCodePair.Builder] {
    def apply(): Builder = new Builder(
      __id = 0,
      __code = 0,
      `_unknownFields__` = null
    )
    def apply(`_message__`: com.mass.tdm.protobuf.tree.IdCodePair): Builder = new Builder(
        __id = _message__.id,
        __code = _message__.code,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = com.mass.tdm.protobuf.tree.IdCodePair.Builder()
  def newBuilder(`_message__`: com.mass.tdm.protobuf.tree.IdCodePair): Builder = com.mass.tdm.protobuf.tree.IdCodePair.Builder(_message__)
  implicit class IdCodePairLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.mass.tdm.protobuf.tree.IdCodePair]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.mass.tdm.protobuf.tree.IdCodePair](_l) {
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def code: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.code)((c_, f_) => c_.copy(code = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val CODE_FIELD_NUMBER = 2
  def of(
    id: _root_.scala.Int,
    code: _root_.scala.Int
  ): _root_.com.mass.tdm.protobuf.tree.IdCodePair = _root_.com.mass.tdm.protobuf.tree.IdCodePair(
    id,
    code
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[com.mass.tdm.protobuf.IdCodePair])
}
