// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.mass.tdm.protobuf.tree

@SerialVersionUID(0L)
final case class IdCodePart(
    partId: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
    idCodeList: _root_.scala.Seq[com.mass.tdm.protobuf.tree.IdCodePair] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[IdCodePart] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = partId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(1, __value)
        }
      };
      idCodeList.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = partId
        if (!__v.isEmpty) {
          _output__.writeBytes(1, __v)
        }
      };
      idCodeList.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withPartId(__v: _root_.com.google.protobuf.ByteString): IdCodePart = copy(partId = __v)
    def clearIdCodeList = copy(idCodeList = _root_.scala.Seq.empty)
    def addIdCodeList(__vs: com.mass.tdm.protobuf.tree.IdCodePair*): IdCodePart = addAllIdCodeList(__vs)
    def addAllIdCodeList(__vs: Iterable[com.mass.tdm.protobuf.tree.IdCodePair]): IdCodePart = copy(idCodeList = idCodeList ++ __vs)
    def withIdCodeList(__v: _root_.scala.Seq[com.mass.tdm.protobuf.tree.IdCodePair]): IdCodePart = copy(idCodeList = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = partId
          if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 2 => idCodeList
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PByteString(partId)
        case 2 => _root_.scalapb.descriptors.PRepeated(idCodeList.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.mass.tdm.protobuf.tree.IdCodePart
    // @@protoc_insertion_point(GeneratedMessage[com.mass.tdm.protobuf.IdCodePart])
}

object IdCodePart extends scalapb.GeneratedMessageCompanion[com.mass.tdm.protobuf.tree.IdCodePart] with scalapb.HasBuilder[com.mass.tdm.protobuf.tree.IdCodePart] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.mass.tdm.protobuf.tree.IdCodePart] with scalapb.HasBuilder[com.mass.tdm.protobuf.tree.IdCodePart] = this
  def merge(`_message__`: com.mass.tdm.protobuf.tree.IdCodePart, `_input__`: _root_.com.google.protobuf.CodedInputStream): com.mass.tdm.protobuf.tree.IdCodePart = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.mass.tdm.protobuf.tree.IdCodePart] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.mass.tdm.protobuf.tree.IdCodePart(
        partId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY),
        idCodeList = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[com.mass.tdm.protobuf.tree.IdCodePair]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TreeProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TreeProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = com.mass.tdm.protobuf.tree.IdCodePair
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.mass.tdm.protobuf.tree.IdCodePart(
    partId = _root_.com.google.protobuf.ByteString.EMPTY,
    idCodeList = _root_.scala.Seq.empty
  )
  final class Builder private (
    private var __partId: _root_.com.google.protobuf.ByteString,
    private val __idCodeList: _root_.scala.collection.immutable.VectorBuilder[com.mass.tdm.protobuf.tree.IdCodePair],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[com.mass.tdm.protobuf.tree.IdCodePart] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __partId = _input__.readBytes()
          case 18 =>
            __idCodeList += _root_.scalapb.LiteParser.readMessage[com.mass.tdm.protobuf.tree.IdCodePair](_input__)
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): com.mass.tdm.protobuf.tree.IdCodePart = {
      com.mass.tdm.protobuf.tree.IdCodePart(
        partId = __partId,
        idCodeList = __idCodeList.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[com.mass.tdm.protobuf.tree.IdCodePart, com.mass.tdm.protobuf.tree.IdCodePart.Builder] {
    def apply(): Builder = new Builder(
      __partId = _root_.com.google.protobuf.ByteString.EMPTY,
      __idCodeList = new _root_.scala.collection.immutable.VectorBuilder[com.mass.tdm.protobuf.tree.IdCodePair],
      `_unknownFields__` = null
    )
    def apply(`_message__`: com.mass.tdm.protobuf.tree.IdCodePart): Builder = new Builder(
        __partId = _message__.partId,
        __idCodeList = new _root_.scala.collection.immutable.VectorBuilder[com.mass.tdm.protobuf.tree.IdCodePair] ++= _message__.idCodeList,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = com.mass.tdm.protobuf.tree.IdCodePart.Builder()
  def newBuilder(`_message__`: com.mass.tdm.protobuf.tree.IdCodePart): Builder = com.mass.tdm.protobuf.tree.IdCodePart.Builder(_message__)
  implicit class IdCodePartLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.mass.tdm.protobuf.tree.IdCodePart]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.mass.tdm.protobuf.tree.IdCodePart](_l) {
    def partId: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.partId)((c_, f_) => c_.copy(partId = f_))
    def idCodeList: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[com.mass.tdm.protobuf.tree.IdCodePair]] = field(_.idCodeList)((c_, f_) => c_.copy(idCodeList = f_))
  }
  final val PART_ID_FIELD_NUMBER = 1
  final val ID_CODE_LIST_FIELD_NUMBER = 2
  def of(
    partId: _root_.com.google.protobuf.ByteString,
    idCodeList: _root_.scala.Seq[com.mass.tdm.protobuf.tree.IdCodePair]
  ): _root_.com.mass.tdm.protobuf.tree.IdCodePart = _root_.com.mass.tdm.protobuf.tree.IdCodePart(
    partId,
    idCodeList
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[com.mass.tdm.protobuf.IdCodePart])
}
