// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.mass.tdm.protobuf.tree

object TreeProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.mass.tdm.protobuf.tree.IdCodePair,
      com.mass.tdm.protobuf.tree.IdCodePart,
      com.mass.tdm.protobuf.tree.TreeMeta,
      com.mass.tdm.protobuf.tree.Node
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgp0cmVlLnByb3RvEhVjb20ubWFzcy50ZG0ucHJvdG9idWYiRAoKSWRDb2RlUGFpchIXCgJpZBgBIAEoBUIH4j8EEgJpZFICa
  WQSHQoEY29kZRgCIAEoBUIJ4j8GEgRjb2RlUgRjb2RlIogBCgpJZENvZGVQYXJ0EiQKB3BhcnRfaWQYASABKAxCC+I/CBIGcGFyd
  ElkUgZwYXJ0SWQSVAoMaWRfY29kZV9saXN0GAIgAygLMiEuY29tLm1hc3MudGRtLnByb3RvYnVmLklkQ29kZVBhaXJCD+I/DBIKa
  WRDb2RlTGlzdFIKaWRDb2RlTGlzdCJpCghUcmVlTWV0YRIqCgltYXhfbGV2ZWwYASABKAVCDeI/ChIIbWF4TGV2ZWxSCG1heExld
  mVsEjEKDGlkX2NvZGVfcGFydBgCIAMoDEIP4j8MEgppZENvZGVQYXJ0UgppZENvZGVQYXJ0IvEBCgROb2RlEhcKAmlkGAEgASgFQ
  gfiPwQSAmlkUgJpZBIsCglwcm9iYWxpdHkYAiABKAJCDuI/CxIJcHJvYmFsaXR5Uglwcm9iYWxpdHkSMQoMbGVhZl9jYXRlX2lkG
  AMgASgFQg/iPwwSCmxlYWZDYXRlSWRSCmxlYWZDYXRlSWQSJAoHaXNfbGVhZhgEIAEoCEIL4j8IEgZpc0xlYWZSBmlzTGVhZhIqC
  gllbWJlZF92ZWMYBSADKAJCDeI/ChIIZW1iZWRWZWNSCGVtYmVkVmVjEh0KBGRhdGEYBiABKAxCCeI/BhIEZGF0YVIEZGF0YWIGc
  HJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}