// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.mass.dr.protobuf.item_mapping

@SerialVersionUID(0L)
final case class Path(
    index: _root_.scala.Seq[_root_.scala.Int] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Path] {
    private[this] def indexSerializedSize = {
      if (__indexSerializedSizeField == 0) __indexSerializedSizeField = {
        var __s: _root_.scala.Int = 0
        index.foreach(__i => __s += _root_.com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(__i))
        __s
      }
      __indexSerializedSizeField
    }
    @transient private[this] var __indexSerializedSizeField: _root_.scala.Int = 0
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      if (index.nonEmpty) {
        val __localsize = indexSerializedSize
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__localsize) + __localsize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      if (index.nonEmpty) {
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(indexSerializedSize)
        index.foreach(_output__.writeInt32NoTag)
      };
      unknownFields.writeTo(_output__)
    }
    def clearIndex = copy(index = _root_.scala.Seq.empty)
    def addIndex(__vs: _root_.scala.Int*): Path = addAllIndex(__vs)
    def addAllIndex(__vs: Iterable[_root_.scala.Int]): Path = copy(index = index ++ __vs)
    def withIndex(__v: _root_.scala.Seq[_root_.scala.Int]): Path = copy(index = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => index
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(index.iterator.map(_root_.scalapb.descriptors.PInt(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.mass.dr.protobuf.item_mapping.Path
    // @@protoc_insertion_point(GeneratedMessage[com.mass.dr.protobuf.Path])
}

object Path extends scalapb.GeneratedMessageCompanion[com.mass.dr.protobuf.item_mapping.Path] with scalapb.HasBuilder[com.mass.dr.protobuf.item_mapping.Path] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.mass.dr.protobuf.item_mapping.Path] with scalapb.HasBuilder[com.mass.dr.protobuf.item_mapping.Path] = this
  def merge(`_message__`: com.mass.dr.protobuf.item_mapping.Path, `_input__`: _root_.com.google.protobuf.CodedInputStream): com.mass.dr.protobuf.item_mapping.Path = newBuilder(_message__).merge(_input__).result()
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.mass.dr.protobuf.item_mapping.Path] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.mass.dr.protobuf.item_mapping.Path(
        index = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[_root_.scala.Int]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ItemMappingProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ItemMappingProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.mass.dr.protobuf.item_mapping.Path(
    index = _root_.scala.Seq.empty
  )
  final class Builder private (
    private val __index: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int],
    private var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder
  ) extends _root_.scalapb.MessageBuilder[com.mass.dr.protobuf.item_mapping.Path] {
    def merge(`_input__`: _root_.com.google.protobuf.CodedInputStream): this.type = {
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __index += _input__.readInt32()
          case 10 => {
            val length = _input__.readRawVarint32()
            val oldLimit = _input__.pushLimit(length)
            while (_input__.getBytesUntilLimit > 0) {
              __index += _input__.readInt32()
            }
            _input__.popLimit(oldLimit)
          }
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      this
    }
    def result(): com.mass.dr.protobuf.item_mapping.Path = {
      com.mass.dr.protobuf.item_mapping.Path(
        index = __index.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
  }
  object Builder extends _root_.scalapb.MessageBuilderCompanion[com.mass.dr.protobuf.item_mapping.Path, com.mass.dr.protobuf.item_mapping.Path.Builder] {
    def apply(): Builder = new Builder(
      __index = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int],
      `_unknownFields__` = null
    )
    def apply(`_message__`: com.mass.dr.protobuf.item_mapping.Path): Builder = new Builder(
        __index = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Int] ++= _message__.index,
        `_unknownFields__` = new _root_.scalapb.UnknownFieldSet.Builder(_message__.unknownFields)
    )
  }
  def newBuilder: Builder = com.mass.dr.protobuf.item_mapping.Path.Builder()
  def newBuilder(`_message__`: com.mass.dr.protobuf.item_mapping.Path): Builder = com.mass.dr.protobuf.item_mapping.Path.Builder(_message__)
  implicit class PathLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.mass.dr.protobuf.item_mapping.Path]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.mass.dr.protobuf.item_mapping.Path](_l) {
    def index: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Int]] = field(_.index)((c_, f_) => c_.copy(index = f_))
  }
  final val INDEX_FIELD_NUMBER = 1
  def of(
    index: _root_.scala.Seq[_root_.scala.Int]
  ): _root_.com.mass.dr.protobuf.item_mapping.Path = _root_.com.mass.dr.protobuf.item_mapping.Path(
    index
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[com.mass.dr.protobuf.Path])
}
